site:
  title: Open Liberty Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://antora.mybluemix.net/docs
  start_page: general::logging.adoc
content:
  sources:
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/general
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/config
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: src/main/content/ui/build/ui-bundle.zip
    snapshot: true    
  default_layout: general-layout
    