site:
  title: Open Liberty Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://openliberty.io/docs
  start_page: general::logging.adoc
content:
  sources:
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/general
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/config
# ui:
#   bundle:
#     url: src/main/content/ui/build/ui-bundle.zip
#   default_layout: general-reference
    