memory: 384M
instances: 1
disk_quota: 1256M
path: ../target/openliberty.war
buildpack: liberty-for-java
timeout: 180

env:
  JBP_CONFIG_LIBERTY: 'app_archive: {features: ["jaxrs-2.1","cdi-2.0","concurrent-1.0","jsonb-1.0","webCache-1.0","mpRestClient-1.3","concurrent-1.0"]}'
